name: TeamUnityBuild

on:
  workflow_dispatch: {}
  schedule:
      # UTCなので9時間引いた値 JST換算だと午前3時
      - cron: '0 18 * * *'

jobs:
  build:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Build
        # 指定したcmdファイルを実行する
        run: ${{ secrets.UNITY_BUILD_PATH }}team-c-build.cmd

  message:
    runs-on: [self-hosted, Windows]
    needs: build
    if: ${{ failure() }}
    steps:
      - name: Discord Post
        run:
          Invoke-WebRequest -Headers @{"Content-Type"="application/json"} -Method Post -Body "{`"content`":`"${{ secrets.DISCORD_MESSAGE }}`"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
