name: TeamUnityBuild

on:
  workflow_dispatch: {}
  schedule:
      # UTCなので9時間引いた値 JST換算だと午前3時
      - cron: '0 18 * * *'

jobs:
  build:
    runs-on: [self-hosted, Windows]
    steps:
      # - name: Checkout
      #   # このGitHub Actionsが実行される前に必要なアクションを指定 (今回はチェックアウトを行うアクション)
      #   uses: actions/checkout@v2
      #   with:
      #     # クローンする際にローカルリポジトリをクリーンにするかどうかを指定
      #     clean: false
      #     # LFSを使用するかどうかを指定
      #     lfs: false
      - name: Build
        # 指定したcmdファイルを実行する
        run: ${{ secrets.UNITY_BUILD_PATH }}team-c-build.cmd

  message:
    runs-on: [self-hosted, Windows]
    if: ${{ failure()}}
    steps:
      - name: Discord Post
        run:
          Invoke-WebRequest -Headers @{"Content-Type"="application/json"} -Method Post -Body "{`"content`":`"${{ secrets.DISCORD_MESSAGE }}`"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
