name: TeamUnityBuild

on:
  workflow_dispatch: {}
  schedule:
      # UTCなので9時間引いた値 JST換算だと午前3時
      - cron: '0 18 * * *'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: echo test
        run: echo "test"
  # hook:
  #   permissions:
  #     contents: write
  #     actions: read
  #     checks: write
  #     deployments: write

  #   uses: VGA-Team2024/Foundation/.github/workflows/UnityBuild.yml@develop
  #   with:
  #     unity_build_cmd_name: team-c-build

    # secrets:
    #   secrets_key: ${{ secrets.SECRET_KEY }}
    #   project_id: Team2024-Project

  #build:
   ## Self-hosted runnerを使用時にはruns-on: self-hostedを指定する
    #runs-on: [self-hosted, default]

    #steps:
      #- name: Checkout
        ## このGitHub Actionsが実行される前に必要なアクションを指定 (今回はチェックアウトを行うアクション)
        #uses: actions/checkout@v2
        #with:
          ## クローンする際にローカルリポジトリをクリーンにするかどうかを指定
          #clean: false
          ## LFSを使用するかどうかを指定
          #lfs: false
      #- name: Build
        ## 指定したcmdファイルを実行する
        #run: ${{ secrets.UNITY_BUILD_PATH }}team-c-build.cmd

  #message:
    #runs-on: self-hosted
    #if: ${{ failure()}}
    #steps:
      #- name: Discord Post
        #run:
          #Invoke-WebRequest -Headers @{"Content-Type"="application/json"} -Method Post -Body "{`"content`":`"UnityBuild Failed <@605717872605528091> :munou:`"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
