# このGitHub Actionsの名前定義
name: Unity Build

# このGitHub Actionsが実行されるトリガーを定義
on:
  # 手動のみで実行する場合はworkflow_dispatchを指定
  workflow_dispatch: {}
  schedule:
      # UTCなので9時間引いた値 JST換算だと午前3時
      - cron: '0 18 * * *'

jobs:
  hook:
    uses: VGA-Team2024/Foundation/.github/workflows/UnityBuild.yaml@develop
    secrets:
      secrets_key: ${{ secrets.SECRET_KEY }}
      project_id: Team2024-Project

  #build:
   ## Self-hosted runnerを使用時にはruns-on: self-hostedを指定する
    #runs-on: [self-hosted, default]

    #steps:
      #- name: Checkout
        ## このGitHub Actionsが実行される前に必要なアクションを指定 (今回はチェックアウトを行うアクション)
        #uses: actions/checkout@v2
        #with:
          ## クローンする際にローカルリポジトリをクリーンにするかどうかを指定
          #clean: false
          ## LFSを使用するかどうかを指定
          #lfs: false
      #- name: Build
        ## 指定したcmdファイルを実行する
        #run: ${{ secrets.UNITY_BUILD_PATH }}team-c-build.cmd

  #message:
    #runs-on: self-hosted
    #if: ${{ failure()}}
    #steps:
      #- name: Discord Post
        #run:
          #Invoke-WebRequest -Headers @{"Content-Type"="application/json"} -Method Post -Body "{`"content`":`"UnityBuild Failed <@605717872605528091> :munou:`"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
