name: Unity Build

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: select build
        if: github.repository == 'VGA-Team2024/TeamC'
        run: echo "team-c-build"

    #   - name: Build
    #     run: ${{ secrets.UNITY_BUILD_PATH }}${{ secrets.UNITY_BUILD_CMD_NAME }}.cmd

# 環境変数の受け渡しのみテストするので、コメントアウト
#   build:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           clean: false
#           lfs: false
#       - name: Build
#         run: ${{ secrets.UNITY_BUILD_PATH }}team-b-build.cmd


#   message:
#     runs-on: self-hosted
#     needs: build
#     if: ${{ failure()}}
#     steps:
#       - name: Discord Post
#         run:
#           Invoke-WebRequest -Headers @{"Content-Type"="application/json"} -Method Post -Body "{`"content`":`"Buildに失敗しました :munou:`"}" ${{ secrets.DISCORD_WEBHOOK_URL }}